Munet1/Munet1/urls.py
import xadmin


from django.urls import path, re_path, include
from django.views.static import serve
from .settings import MEDIA_ROOT
# , STATIC_ROOT

from users.views import LoginView, RegisterView, ActiveUserView, IndexView
from users.views import ForgetPwdView, ResetView, ModifyPwdView, LogoutView

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    # 登陆类url
    re_path(r'^$', IndexView.as_view(), name='index'),
    re_path(r'^login/$', LoginView.as_view(), name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^register/$', RegisterView.as_view(), name='register'),
    re_path(r'^forget/$',  ForgetPwdView.as_view(), name='forget'),

    # captcha库
    re_path(r'^captcha/', include('captcha.urls')),

    # 邮箱激活验证链接
    re_path(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    re_path(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name='user_reset'),
    # re_path(r'^update_email/(?P<reset_code>.*)/$', ResetView.as_view(), name='user_reset'),
    re_path(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),

    # 讲师url
    re_path(r'^teacher/', include('Organization.urls')),

    # 课程机构url
    re_path(r'^org_list/', include('Organization.urls')),

    # 配置上传文件访问处理
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),

    # 公开课首页
    re_path(r'^course_list/', include('Courses.urls')),

    # 个人中心
    re_path(r'^user/', include('users.urls')),
]


# 全局404
handler404 = 'users.views.page_404'
# 全局500
handler500 = 'users.views.page_500'

Munet1/apps/Courses/models.py
from datetime import datetime

from django.db import models

from Organization.models import CourseOrg, Teacher

# Create your models here.


# 课程表
class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name='课程机构', null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name=u"课程名")
    desc = models.CharField(max_length=200, verbose_name=u"课程描述")
    detail = models.TextField(verbose_name=u'课程详情')
    category = models.CharField(max_length=20, default='', verbose_name='课程类别')
    difficulty = models.CharField(max_length=10,
                                  choices=(('ezsy', u'简单'), ('mid', u'中等'),
                                           ('difficult', u"困难")),
                                  verbose_name=u'课程难度')
    learn_times = models.IntegerField(default=0, verbose_name=u'分钟数')
    students = models.IntegerField(default=0, verbose_name=u"学习人数")
    collection_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    class_image = models.ImageField(upload_to='image/courses', verbose_name=u'课程封面')
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    tag = models.CharField(default='', max_length=15, verbose_name='课程标签')
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name='课程讲师', null=True, blank=True)
    course_required = models.CharField(max_length=100, default='', verbose_name='课程须知')
    teacher_message = models.CharField(max_length=100, default='', verbose_name='教师告诉你')

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    # 获取课程章节数
    def get_lesson_count(self):
        return self.lesson_set.all().count()

    # 获取章节信息
    def get_lesson(self):
        return self.lesson_set.all()


# 章节表
class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'课程名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    def __str__(self):
        return self.name

    def get_lesson_video(self):
        return self.vedio_set.all()

    class Meta:
        verbose_name = u'章节信息'
        verbose_name_plural = verbose_name


# 视频表
class Vedio(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    url = models.CharField(max_length=200, default='', verbose_name='访问链接')
    video_times = models.IntegerField(default=0, verbose_name=u'分钟数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'课程视频'
        verbose_name_plural = verbose_name


# 下载资源表
class CourseResource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'资源名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    download = models.FileField(max_length=100, upload_to='course/resource', verbose_name=u'资源文件')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

Munet1/templates/actice_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<P>啊哦！该链接已失效</P>
</body>
</html>

Munet1/templates/course-list.html
{% extends 'base.html' %}
{% block title %}公开课 - 在线云课堂{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
    <div class="wp">
        <div class="list" style="margin-top:0;">
            <div class="left layout">
                <div class="head">
                    <ul class="tab_header">
                        <li class="{% if sort_course == '' %}active{% endif %}"><a href="?sort=">最新 </a></li>
                        <li class="{% ifequal sort_course 'hot' %}active{% endifequal %}"><a href="?sort=hot">最热门</a></li>
                        <li class="{% ifequal sort_course 'students' %}active{% endifequal %}"><a href="?sort=students">参与人数</a></li>
                    </ul>
                </div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
                        <div class="group_list">
                            {% for course in courses %}
                                <div class="box">
                                <a href="{% url 'course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.class_image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href="{% url 'org_homepage' course.course_org.id %}"><span class="fl">来自{{ course.course_org }}</span></a>
                                    <span class="star fr  notlogin" data-favid="15">
                                        {{ course.collection_nums }}
                                    </span>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="pageturn">
                            <ul class="pagelist">
                                {% if courses.has_previous %}
                                    <li class="long"><a href="?sort={{ sort_course }}&page={{ courses.previous_page_number }}">上一页</a></li>
                                {% endif %}
                                {% for page in courses.paginator.page_range %}
                                    {% if page == courses.number %}
                                        <li class="active"><a href="?sort={{ sort_course }}&page={{ page }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?sort={{ sort_course }}&page={{ page }}" class="page">{{ page }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if courses.has_next %}
                                    <li class="long"><a href="?sort={{ sort_course }}&page={{ courses.next_page_number }}">下一页</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="right layout">
                <div class="head">热门课程推荐</div>
                <div class="group_recommend">
                    {% for high in high_click %}
                        <dl>
                        <dt>
                            <a target="_blank" href="{% url 'course_detail' high.id %}">
                                <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ high.class_image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <a target="_blank" href="{% url 'course_detail' high.id %}"><h2>{{ high.name }}</h2></a>
                            <span class="fl">难度：<i class="key">{{ high.get_difficulty_display }}</i></span>
                        </dd>
                    </dl>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Munet1/templates/course-video.html
{% extends 'base.html' %}
{% block title %}{{ course.name }}-章节信息- 在线云课堂{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="\">首页</a>></li>
                    <li><a href="{% url 'course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course_detail' course_id %}">课程详情</a>></li>
                    <li>章节信息</li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block content %}
    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value"><strong>{{ course.get_difficulty_display}}</strong></span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.learn_times }}分钟</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.students }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course_video' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="" href="{% url 'course_comment' course_id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <div id="notice" class="clearfix">
                            <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                        </div>

                        <div class="mod-chapters">
                            {% for lesson in course.get_lesson %}
                                <div class="chapter chapter-active" >
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">
                                        {% for video in lesson.get_lesson_video %}
                                        <li>
                                            <a target="_blank" href="{% url 'course_play' video.id %}" class="J-media-item studyvideo">{{ video.name }} ({{ video.video_times }})
                                                <i class="study-state"></i>
                                            </a>
                                        </li>
                                            {% endfor %}
                                    </ul>
                                </div>
                            {% endfor %}
                        </div>


                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for resource in all_resource %}
                                    <li>
                                        <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp{{ resource.name }}</span>
                                        <a href="{{ MEDIA_URL }}{{ resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="/u/315464/courses?sort=publish" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacher.teacher_image }}' width='80' height='80' />
                                    </a>
                                    <span class="tit">
                                        <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
                                    </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.course_required }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_message }}</dd>
                                    </dl>
                                </div>
                            </div>



                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in recommend_course %}
                                                <li class="curr">
                                                    <a href="{% url 'course_detail' course.id %}" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ course.class_image }}" alt="{{ course.name }}">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">
                                            <li class="curr">
                                                <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                                    <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                                    <span class="name autowrap">Java工程师</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}
{% block customer_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">

    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
{% endblock %}

Munet1/templates/email_return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮件发送成功</title>
</head>
<body>
<p>邮件已发送成功</p>
<a href="/login/">点击返回</a>
</body>
</html>

Munet1/templates/index.html
{% extends 'base.html' %}
{% block title %}
    在线云课堂 - 在线学习平台！
{% endblock %}
{% block bread %}
{% endblock %}
{% block content %}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in all_banners %}
                            <li>
                            <a href="{{ banner.url }}">
                                <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>

        </div>


    </div>

    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="/static/images/feature1.png"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="/static/images/feature2.png"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="/static/images/feature3.png"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="/static/images/feature4.png"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>

    <section>
        <div class="module">
            <div class="wp">
                <h1>公开课程</h1>
                <div class="module1 eachmod">
                    <div class="module1_1 left">
                        <img width="228" height="614" src="/static/images/module1_1.jpg"/>
                        <p class="fisrt_word">名师授课<br/>专业权威</p>
                        <a class="more" href="{% url 'course_list' %}">查看更多课程 ></a>
                    </div>
                    <div class="right group_list">
                        <div class="module1_2 box">
                            <div class="imgslide2">
                                <ul class="imgs">
                                    {% for course in ad_course_banner %}
                                        <li>
                                        <a href="{% url 'course_detail' course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ course.class_image }}" />
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="unslider-arrow2 prev"></div>
                            <div class="unslider-arrow2 next"></div>
                        </div>
                    {% for course in all_courses %}
                        <div class="module1_{{ forloop.counter | add:2 }} box">
                            <a href="{% url 'course_detail' course.id %}">
                                <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.class_image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course_detail' course.id %}">
                                    <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                </a>
                                <span class="fl">难度：<i class="key">{{ course.get_difficulty_display }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                                <span class="star fr">{{ course.course_org.collection_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="module greybg">
            <div class="wp">
                <h1>课程机构</h1>
                <div class="module3 eachmod">
                    <div class="module3_1 left">
                        <img width="228" height="463" src="/static/images/module3_1.jpg"/>
                        <p class="fisrt_word">名校来袭<br/>权威认证</p>
                        <a class="more" href="{% url 'org_list' %}">查看更多机构 ></a>
                    </div>
                    <div class="right">
                        <ul>
                            {% for org in all_orgs %}
                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                <a href="{% url 'org_homepage' org.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.Org_image }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block customer_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

Munet1/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
</head>
<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                {% for error in reset_form.errors.values %}
                            {{ error }}
                {% endfor %}
                {{ msg }}
                <li class="button">
                    <input type="submit" value="提交">
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>